%% load the merkmal
load('can_vmps_yawrate_chassis.mat', 'Effwert')
Daten(:,1)=Effwert(:,1);%Eff(luft strom koeperschall)
load('can_vmps_rollrate_chassis.mat', 'Effwert')
Daten(:,2)=Effwert(:,1);%Eff(luft strom koeperschall)
load('can_vmps_pitchrate_chassis.mat', 'Effwert')
Daten(:,3)=Effwert(:,1);%Eff(luft strom koeperschall)
load('can_mm73_rollrate_chassis.mat', 'Effwert')
Daten(:,4)=Effwert(:,1);%Eff(luft strom koeperschall)
load('can_mm73_acceleration_chassis_zneg.mat', 'Effwert')
Daten(:,5)=Effwert(:,1);%Eff(luft strom koeperschall)
load('can_mm72_pitchrate_chassis.mat', 'Effwert')
Daten(:,6)=Effwert(:,1);%Eff(luft strom koeperschall)
load('can_mm72_acceleration_chassis_zneg.mat', 'Effwert')
Daten(:,7)=Effwert(:,1);%Eff(luft strom koeperschall)
load('can_mm71_yawrate_chassis.mat', 'Effwert')
Daten(:,8)=Effwert(:,1);%Eff(luft strom koeperschall)
load('analog_daqmx_rollnoise_right.mat', 'Effwert')
Daten(:,9)=Effwert(:,1);%Eff(luft strom koeperschall)
load('analog_daqmx_acceleration_supension_z_right.mat', 'Effwert')
Daten(:,10)=Effwert(:,1);%Eff(luft strom koeperschall)
%% merkmale
load('can_vmps_yawrate_chassis.mat', 'FFTwert_max')
Daten(:,11)=FFTwert_max(:,1);%Eff(luft strom koeperschall)
load('can_vmps_rollrate_chassis.mat', 'FFTwert_max')
Daten(:,12)=FFTwert_max(:,1);%Eff(luft strom koeperschall)
load('can_vmps_pitchrate_chassis.mat', 'FFTwert_max')
Daten(:,13)=FFTwert_max(:,1);%Eff(luft strom koeperschall)
load('can_mm73_rollrate_chassis.mat', 'FFTwert_max')
Daten(:,14)=FFTwert_max(:,1);%Eff(luft strom koeperschall)
load('can_mm73_acceleration_chassis_zneg.mat', 'FFTwert_max')
Daten(:,15)=FFTwert_max(:,1);%Eff(luft strom koeperschall)
load('can_mm72_pitchrate_chassis.mat', 'FFTwert_max')
Daten(:,16)=FFTwert_max(:,1);%Eff(luft strom koeperschall)
load('can_mm72_acceleration_chassis_zneg.mat', 'FFTwert_max')
Daten(:,17)=FFTwert_max(:,1);%Eff(luft strom koeperschall)
load('can_mm71_yawrate_chassis.mat', 'FFTwert_max')
Daten(:,18)=FFTwert_max(:,1);%Eff(luft strom koeperschall)
load('analog_daqmx_rollnoise_right.mat', 'FFTwert_max')
Daten(:,19)=FFTwert_max(:,1);%Eff(luft strom koeperschall)
load('analog_daqmx_acceleration_supension_z_right.mat', 'FFTwert_max')
Daten(:,20)=FFTwert_max(:,1);%Eff(luft strom koeperschall)
%% merkmale
load('can_vmps_yawrate_chassis.mat', 'FFTwert_mean')
Daten(:,21)=FFTwert_mean(:,1);%Eff(luft strom koeperschall)
load('can_vmps_rollrate_chassis.mat', 'FFTwert_mean')
Daten(:,22)=FFTwert_mean(:,1);%Eff(luft strom koeperschall)
load('can_vmps_pitchrate_chassis.mat', 'FFTwert_mean')
Daten(:,23)=FFTwert_mean(:,1);%Eff(luft strom koeperschall)
load('can_mm73_rollrate_chassis.mat', 'FFTwert_mean')
Daten(:,24)=FFTwert_mean(:,1);%Eff(luft strom koeperschall)
load('can_mm73_acceleration_chassis_zneg.mat', 'FFTwert_mean')
Daten(:,25)=FFTwert_mean(:,1);%Eff(luft strom koeperschall)
load('can_mm72_pitchrate_chassis.mat', 'FFTwert_mean')
Daten(:,26)=FFTwert_mean(:,1);%Eff(luft strom koeperschall)
load('can_mm72_acceleration_chassis_zneg.mat', 'FFTwert_mean')
Daten(:,27)=FFTwert_mean(:,1);%Eff(luft strom koeperschall)
load('can_mm71_yawrate_chassis.mat', 'FFTwert_mean')
Daten(:,28)=FFTwert_mean(:,1);%Eff(luft strom koeperschall)
load('analog_daqmx_rollnoise_right.mat', 'FFTwert_mean')
Daten(:,29)=FFTwert_mean(:,1);%Eff(luft strom koeperschall)
load('analog_daqmx_acceleration_supension_z_right.mat', 'FFTwert_mean')
Daten(:,30)=FFTwert_mean(:,1);%Eff(luft strom koeperschall)
%% merkmale
load('can_vmps_yawrate_chassis.mat', 'FFTwert_varianz')
Daten(:,31)=FFTwert_varianz(:,1);%Eff(luft strom koeperschall)
load('can_vmps_rollrate_chassis.mat', 'FFTwert_varianz')
Daten(:,32)=FFTwert_varianz(:,1);%Eff(luft strom koeperschall)
load('can_vmps_pitchrate_chassis.mat', 'FFTwert_varianz')
Daten(:,33)=FFTwert_varianz(:,1);%Eff(luft strom koeperschall)
load('can_mm73_rollrate_chassis.mat', 'FFTwert_varianz')
Daten(:,34)=FFTwert_varianz(:,1);%Eff(luft strom koeperschall)
load('can_mm73_acceleration_chassis_zneg.mat', 'FFTwert_varianz')
Daten(:,35)=FFTwert_varianz(:,1);%Eff(luft strom koeperschall)
load('can_mm72_pitchrate_chassis.mat', 'FFTwert_varianz')
Daten(:,36)=FFTwert_varianz(:,1);%Eff(luft strom koeperschall)
load('can_mm72_acceleration_chassis_zneg.mat', 'FFTwert_varianz')
Daten(:,37)=FFTwert_varianz(:,1);%Eff(luft strom koeperschall)
load('can_mm71_yawrate_chassis.mat', 'FFTwert_varianz')
Daten(:,38)=FFTwert_varianz(:,1);%Eff(luft strom koeperschall)
load('analog_daqmx_rollnoise_right.mat', 'FFTwert_mean')
Daten(:,39)=FFTwert_varianz(:,1);%Eff(luft strom koeperschall)
load('analog_daqmx_acceleration_supension_z_right.mat', 'FFTwert_mean')
Daten(:,40)=FFTwert_varianz(:,1);%Eff(luft strom koeperschall)
%% merkmale
load('can_vmps_yawrate_chassis.mat', 'Woelbung')
Daten(:,41)=Woelbung(:,1);%Eff(luft strom koeperschall)
load('can_vmps_rollrate_chassis.mat', 'Woelbung')
Daten(:,42)=Woelbung(:,1);%Eff(luft strom koeperschall)
load('can_vmps_pitchrate_chassis.mat', 'Woelbung')
Daten(:,43)=Woelbung(:,1);%Eff(luft strom koeperschall)
load('can_mm73_rollrate_chassis.mat', 'Woelbung')
Daten(:,44)=Woelbung(:,1);%Eff(luft strom koeperschall)
load('can_mm73_acceleration_chassis_zneg.mat', 'Woelbung')
Daten(:,45)=Woelbung(:,1);%Eff(luft strom koeperschall)
load('can_mm72_pitchrate_chassis.mat', 'Woelbung')
Daten(:,46)=Woelbung(:,1);%Eff(luft strom koeperschall)
load('can_mm72_acceleration_chassis_zneg.mat', 'Woelbung')
Daten(:,47)=Woelbung(:,1);%Eff(luft strom koeperschall)
load('can_mm71_yawrate_chassis.mat', 'Woelbung')
Daten(:,48)=Woelbung(:,1);%Eff(luft strom koeperschall)
load('analog_daqmx_rollnoise_right.mat', 'Woelbung')
Daten(:,49)=Woelbung(:,1);%Eff(luft strom koeperschall)
load('analog_daqmx_acceleration_supension_z_right.mat', 'Woelbung')
Daten(:,50)=Woelbung(:,1);%Eff(luft strom koeperschall)
%% merkmale
load('can_vmps_yawrate_chassis.mat', 'schiefe')
Daten(:,41)=schiefe(:,1);%Eff(luft strom koeperschall)
load('can_vmps_rollrate_chassis.mat', 'schiefe')
Daten(:,42)=schiefe(:,1);%Eff(luft strom koeperschall)
load('can_vmps_pitchrate_chassis.mat', 'schiefe')
Daten(:,43)=schiefe(:,1);%Eff(luft strom koeperschall)
load('can_mm73_rollrate_chassis.mat', 'schiefe')
Daten(:,44)=schiefe(:,1);%Eff(luft strom koeperschall)
load('can_mm73_acceleration_chassis_zneg.mat', 'schiefe')
Daten(:,45)=schiefe(:,1);%Eff(luft strom koeperschall)
load('can_mm72_pitchrate_chassis.mat', 'schiefe')
Daten(:,46)=schiefe(:,1);%Eff(luft strom koeperschall)
load('can_mm72_acceleration_chassis_zneg.mat', 'schiefe')
Daten(:,47)=schiefe(:,1);%Eff(luft strom koeperschall)
load('can_mm71_yawrate_chassis.mat', 'schiefe')
Daten(:,48)=schiefe(:,1);%Eff(luft strom koeperschall)
load('analog_daqmx_rollnoise_right.mat', 'schiefe')
Daten(:,49)=schiefe(:,1);%Eff(luft strom koeperschall)
load('analog_daqmx_acceleration_supension_z_right.mat', 'schiefe')
Daten(:,50)=schiefe(:,1);%Eff(luft strom koeperschall)
%% merkmale
load('can_vmps_yawrate_chassis.mat', 'varianz')
Daten(:,41)=varianz(:,1);%Eff(luft strom koeperschall)
load('can_vmps_rollrate_chassis.mat', 'varianz')
Daten(:,42)=varianz(:,1);%Eff(luft strom koeperschall)
load('can_vmps_pitchrate_chassis.mat', 'varianz')
Daten(:,43)=varianz(:,1);%Eff(luft strom koeperschall)
load('can_mm73_rollrate_chassis.mat', 'varianz')
Daten(:,44)=varianz(:,1);%Eff(luft strom koeperschall)
load('can_mm73_acceleration_chassis_zneg.mat', 'varianz')
Daten(:,45)=varianz(:,1);%Eff(luft strom koeperschall)
load('can_mm72_pitchrate_chassis.mat', 'varianz')
Daten(:,46)=varianz(:,1);%Eff(luft strom koeperschall)
load('can_mm72_acceleration_chassis_zneg.mat', 'varianz')
Daten(:,47)=varianz(:,1);%Eff(luft strom koeperschall)
load('can_mm71_yawrate_chassis.mat', 'varianz')
Daten(:,48)=varianz(:,1);%Eff(luft strom koeperschall)
load('analog_daqmx_rollnoise_right.mat', 'varianz')
Daten(:,49)=varianz(:,1);%Eff(luft strom koeperschall)
load('analog_daqmx_acceleration_supension_z_right.mat', 'varianz')
Daten(:,50)=varianz(:,1);%Eff(luft strom koeperschall)
load('analog_daqmx_acceleration_supension_z_right.mat', 'Label')
Daten(:,51)=Label;


%% normal
for d=1:50
Daten(:,d)=(Daten(:,d)-mean(Daten(:,d)))/std(Daten(:,d));
end
%%
%n=3;
%klassenvector=[79 9];
%Daten=sortrows(Daten,51);
%merkmalvek=addonalgo(Daten(:,1:50),n,klassenvector);

 %traindata=D(:,merkmalvek);
 %testdata=Daten(:,merkmalvek);
%%
%Target=Testdata(:,13);%EKR_Bayes=1-sum(Target~=yfit)/length(Target)
%yfit = trainedClassifier.predictFcn(testdata(:,1:3));
